services:
  - type: worker
    name: maythushar 1
    env: docker
    dockerfilePath: ./Dockerfile
    plan: pro plus
    region: singapore
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    envVars:
      - key: API_ID
        value: "29758428"
      - key: API_HASH
        value: "51f9369e03f78674ca21aee8dfd1c842"
      - key: BOT_TOKEN
        value: "8242918647:AAFzruK1HS2RayQ4HZ01cS-wybR2MjabrAg"
      - key: MONGO_DB_URI
        value: "mongodb+srv://pyaesone:pyaesone@pyaesone.ii8wsxo.mongodb.net/?retryWrites=true&w=majority"
      - key: OWNER_ID
        value: "5821905026"
      - key: LOGGER_ID
        value: "-1002470419378"
      - key: STRING_SESSION
        value: "BQHGE9wAa4SwUSK-zBwhbsXPfF2Jp-8R-Ik4zQojkuTMoi3E0acbI9JGjqX18F5G-AMxfsxxDSGsApZqGNh7dF6Ln-isKCVvtJt0J-SZ6-RaLHGXe5LW-FbjcrdPRxCR9QZTHpoj5725SwOKB9aGzxXyDEMC0XhUMsQ0LyfZM0cel2H1KyojITE9YiJwSylM2xgBopeLvImxIz_KrBQB0u0Bm79GDD07PWxcwo1RDI6kU7mb5iLo6Kyg9msjt4cny5jCpxgkZQ2ouDPM6nx8QspZ1CsxtqTSEkVOSjMfI-FTgYTQJ7igm_AcFv0N9JeoIT9-zGP6HBuc1kyiHdXlxjnnu-y8WQAAAAFbAziCAA"
